Refactor openstad components widgets
openstad/openstad-frontend pull request #331
Opened 2022-03-03 11:45 UTC by nlsvgtr

# Description

Refactor all widgets based on openstad-components.

The main changes are:
Added a parent widget for all generic functionality and configuration, thereby reducing duplicate code and simplifying the specific widgets
Moved loading of the component from the template to a play function for added functionality and automatic reloading after config changes
Moved arrangeFields to the fields.js

Goal is to make it easier to add more openstad-components widgets

## Type of change

Code improvement

## Documentation

N/A

## Tests

Only locally

2022-03-14 15:42 UTC, stijnvandervegt commented on packages/cms/lib/modules/choices-guide-widgets/index.js
>      self.expressMiddleware = {
https://v2.docs.apostrophecms.org/reference/modules/apostrophe-notifications/#expressmiddleware-req-res-next

2022-08-18 12:51 UTC, rudivanhierden requested changes

2022-08-18 12:51 UTC, rudivanhierden commented on packages/cms/lib/modules/arguments-block-widgets/index.js
> +const merge = require('merge');
`merge` does not seem to be included in package.json.

2022-08-18 12:51 UTC, rudivanhierden commented on packages/cms/lib/modules/arguments-block-widgets/public/js/main.js
> +      OpenStadComponents['reactions'].Reactions.renderElement(element, config);
There is no guarantee that `OpenStadComponents` is loaded when the `self.play` function is called due to the way we load the JS file for the React Component. This can be observed when a component is added to the page for the first time. The console will display an error that `OpenStadComponents` is `undefined`. After a refresh it will work as expected.

This isn't just for the `arguments-block` widget, but for all OpenStadComponent widgets loaded this way.

2022-08-22 13:33 UTC, nlsvgtr commented on packages/cms/lib/modules/arguments-block-widgets/index.js
> +const merge = require('merge');
Sad. Fixed.

2022-08-22 13:33 UTC, nlsvgtr commented on packages/cms/lib/modules/choices-guide-widgets/index.js
>      self.expressMiddleware = {
The link you provided shows an explicit use of expressMiddleware, but as you can see [in the apos/express docs](https://v2.docs.apostrophecms.org/reference/modules/apostrophe-express.html#module-specific-middleware) one can use it in other situations as well.

Here it is used because the values are required by the lib/api in the line above, and need to be added before that lb is loaded. I use this construction to make sure the API call is only done when needed, that is when a form is presented to the website editor.

Naming was in Dutch; I did fix that.

2022-10-18 08:58 UTC, nlsvgtr commented on packages/cms/lib/modules/arguments-block-widgets/public/js/main.js
> +      OpenStadComponents['reactions'].Reactions.renderElement(element, config);
Very nice catch. I could not come up with anything better then a loader function. It is added to the parent widget main.js.

Small consolation: The old way did add a script tag for each widget; it does now load files only once.

2022-10-27 13:21 UTC, rudivanhierden approved these changes
Looks good to me! Should the fixes implemented in #368 also be implemented in this PR?

2022-10-27 13:55 UTC, merged