Feature/translate toast
openstad/openstad-frontend pull request #370
Opened 2022-11-07 11:52 UTC by LorenzoJokhan

# Description

Please include
- a summary of the changes
- relevant motivation and context
- a list of any dependencies that are required for this change

## Issue reference

Fixes # (issue)

## Type of change

Is it a new feature, bug fix, code improvement, etc.  
If it is a breaking change what needs to be done to fix that

## Documentation

Is the documentation updated, maybe a link

## Tests

(How) has the change been tested

## Branch

If the branch to merge to is not development

2022-11-07 13:15 UTC, rudivanhierden reviewed
Looking good so far! Just a few questions (and one nitpicky formatting comment)

2022-11-07 13:15 UTC, rudivanhierden commented on packages/cms/lib/modules/openstad-assets/public/css/toast.less
> +    filter: drop-shadow(0px 4px 8px rgba(0, 0, 0, 0.08)) drop-shadow(0px 2px 4px rgba(0, 0, 0, 0.08));}
```suggestion
    filter: drop-shadow(0px 4px 8px rgba(0, 0, 0, 0.08)) drop-shadow(0px 2px 4px rgba(0, 0, 0, 0.08));
}
```

2022-11-07 13:15 UTC, rudivanhierden commented on packages/cms/lib/modules/openstad-global/public/js/always.js
> +}
Where is this method used?

2022-11-07 13:15 UTC, rudivanhierden commented on packages/cms/lib/modules/translation-widgets/public/js/always.js
> +                    error: function(e) {
The error `e` isn't used in this method, so I think we can leave it out?

2022-11-08 08:45 UTC, LorenzoJokhan commented on packages/cms/lib/modules/openstad-assets/public/css/toast.less
> +    filter: drop-shadow(0px 4px 8px rgba(0, 0, 0, 0.08)) drop-shadow(0px 2px 4px rgba(0, 0, 0, 0.08));}
Done

2022-11-08 08:46 UTC, LorenzoJokhan commented on packages/cms/lib/modules/translation-widgets/public/js/always.js
> +                    error: function(e) {
e weggehaald

2022-11-09 08:27 UTC, rudivanhierden requested changes

2022-11-09 08:27 UTC, rudivanhierden commented on packages/cms/lib/modules/openstad-global/public/js/always.js
> +    var userHasSpecialRole = self.openstadUserRole === 'admin' || self.openstadUserRole === 'moderator' || self.openstadUserRole === 'editor';
I think we can use `hasModeratorRights` global variable set in layout.html, (`self.hasModeratorRights` I think in this context?)

2022-11-09 08:27 UTC, rudivanhierden commented on packages/cms/lib/modules/translation-widgets/public/js/always.js
> +    var isNormalUser = !(self.openstadUserRole === 'admin' || self.openstadUserRole === 'moderator' || self.openstadUserRole === 'editor');
Same goes for this check

2022-11-09 08:43 UTC, rudivanhierden approved these changes

2022-11-09 08:43 UTC, merged