Feature/extend arguments widget
openstad/openstad-frontend pull request #404
Opened 2023-06-27 08:56 UTC by LorenzoJokhan

# Description

Please include
- a summary of the changes
- relevant motivation and context
- a list of any dependencies that are required for this change

## Issue reference

Fixes # (issue)

## Type of change

Is it a new feature, bug fix, code improvement, etc.  
If it is a breaking change what needs to be done to fix that

## Documentation

Is the documentation updated, maybe a link

## Tests

(How) has the change been tested

## Branch

If the branch to merge to is not development

2023-07-31 15:04 UTC, rudivanhierden requested changes

2023-07-31 15:04 UTC, rudivanhierden commented on packages/cms/lib/modules/arguments-form-widgets/index.js
The field is still commented so it won't show.

2023-07-31 15:04 UTC, rudivanhierden commented on packages/cms/lib/modules/arguments-widgets/index.js
> +        fields: ['replyingEnabled', 'votingEnabled', 'showLastNameForArguments', 'showLastNameForReactions', 'ideaId']
`showLastNameForArguments` and `showLastNameForReactions` are not defined in this file. I don't think they belong in this PR because they are not within the scope of the requested change — we only need the `ideaId` in this field.

2023-07-31 15:04 UTC, rudivanhierden commented on packages/cms/lib/modules/arguments-widgets/index.js
> +     });
Same goes for this helper — should not be in this PR I think.

2023-08-02 07:50 UTC, LorenzoJokhan commented
https://github.com/openstad/openstad-frontend/pull/416 Vervangt deze PR

2023-08-02 07:50 UTC, closed without merging